### ISSUE TITLE
Group tests by conformance classes

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sensorml20#1]
Up to commit: 9a370c4c8c1914b2b9dfd9f8a2e6e39510b0f4ef, conformance classes were not well specified in the tests scripts (ctl), read me and welcome page.

**Comment by epicureanism** [comment]
We would like to migrate the current CTL version into TestNG since the diffuculties of implementing all the conformance classess under CTL.
We also recommend to separate the conformace classes into smaller issues list based on the category of conformance classes, this can be more focused on the details.

**Comment by bermud** [comment]
If you think testng will be better please go ahead and make the change.
