### ISSUE TITLE
 Improve name of test suite

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-sensorml20#36]
Currently, "Test suite: ets-swecommon20" is displayed as name of test suite on http://cite.opengeospatial.org/te2/.

The name should be the same as the  SensorML 1.0 test suite (Sensor Model Language (SensorML)).

**Comment by epicureanism** [comment]
Test suite: ets-swecommon20 refers to the SWE Common 2.0, and this name should be improved as the name of SWE Common Data Model Encoding Standard (just like the name on OGC official site).
And the name of SensorML 2.0 was correct but with a wrong spec version number which was fixed in ec8a7df80d92693c3350d03c2ec67f8421a02d41
